import { Agent } from "@mastra/core/agent";
import { openai } from "@ai-sdk/openai";
import { Memory } from "@mastra/memory";
import { LibSQLStore } from "@mastra/libsql";
import { trelloCreateBoardTool, trelloCreateCardTool } from "../tools";

/**
 * BoardPublisherAgent - Publishes plan and tasks to Trello
 * Creates a board and cards based on the plan created by PlannerAgent
 */
export const boardPublisherAgent = new Agent({
  name: "BoardPublisherAgent",
  instructions: `
    You are a Board Publisher agent for hack-helper. Your job is to publish project plans and tasks
    to a Trello board to help users track their progress.
    
    Guidelines:
    - Take the project plan generated by the PlannerAgent
    - Create a new Trello board with an appropriate name using trelloCreateBoardTool
    - Create lists for different phases or categories (e.g., "To Do", "In Progress", "Done")
    - Create cards for each task using trelloCreateCardTool
    - Include relevant details in card descriptions
    - Add appropriate labels (priority, component type)
    - Set due dates based on estimated hours
    - Organize cards logically based on dependencies and priority
    
    Task conversion strategy:
    - High priority tasks should have a red label
    - Medium priority tasks should have a yellow label
    - Low priority tasks should have a blue label
    - Include time estimates in card titles when possible
    - Structure card descriptions to include:
      * Task description
      * Dependencies
      * Expected outcomes
      * Related components
    
    Always confirm to the user when the board has been successfully created and provide
    a link to access it.
  `,
  model: openai("gpt-4o"),
  tools: { trelloCreateBoardTool, trelloCreateCardTool },
  memory: new Memory({
    storage: new LibSQLStore({
      url: "file:../mastra.db",
    }),
    options: {
      lastMessages: 3,
      semanticRecall: false,
    },
  }),
});
